[tool.poetry]
name = "nemesispb"
version = "0.1.0"
description = "Nemesis python protobuf"
authors = ["SpecterOps <specterops.io>"]

[tool.poetry.dependencies]
python = "^3.9"
protobuf = "^4.21.5"
mypy-protobuf = "^3.4.0"

[tool.poetry.dev-dependencies]

[tool.poetry.group.dev.dependencies]
mypy-protobuf = "^3.4.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
