apiVersion: v1
kind: Service
metadata:
  name: passwordcracker
  labels:
    app: passwordcracker
    component: enrichment-pipeline
spec:
  type: NodePort
  ports:
    - name: "9090"
      port: 9090
      targetPort: 9090
      nodePort: 31990
  selector:
    app: passwordcracker
status:
  loadBalancer: {}
