{{- if .Values.aws }}
apiVersion: v1
kind: Secret
metadata:
  name: aws-creds
type: Opaque
data:
  aws_access_key_id: {{ .Values.aws.accessKeyId | b64enc }}
  aws_secret_key: {{ .Values.aws.secretKey | b64enc }}
{{ end }}