{{- if .Values.aws }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-config
data:
  aws-bucket: {{ .Values.aws.bucket | quote }}
  aws-default-region: {{ .Values.aws.region | quote }}
  aws-kms-key-alias: {{ .Values.aws.kmsKeyAlias | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: aws-creds
type: Opaque
data:
  aws-access-key-id: {{ .Values.aws.accessKeyId | b64enc }}
  aws-secret-key: {{ .Values.aws.secretKey | b64enc }}
{{- end }}
