apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-users
type: Opaque
data:
  username: {{ default "nemesis" .Values.elasticsearch.username | b64enc }}

  {{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace "elasticsearch-users") | default dict }}
  {{- $existingSecretData := (get $existingSecret "data") | default dict }}
  {{- $password := (get $existingSecretData "password") | default (randAlphaNum 24 | b64enc) }}
  password: {{ $password | quote }}

  roles: {{ "superuser" | b64enc }}