apiVersion: v1
kind: ConfigMap
metadata:
  name: hasura-metadata
data:
  # to export: curl -d '{"type": "export_metadata", "args": {}}' http://localhost:8080/v1/metadata -o hasura_metadata.json
  hasura_metadata.json: |-
    {{- .Files.Get "files/hasura/hasura_metadata.json" | nindent 4 -}}