apiVersion: v1
kind: Secret
metadata:
  name: jupyter-creds
type: Opaque
data:
  {{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace "jupyter-creds") | default dict }}
  {{- $existingSecretData := (get $existingSecret "data") | default dict }}
  {{- $jupyterToken:= (get $existingSecretData "token") }}
  {{- if not $jupyterToken }}
    {{- if .Values.minio.rootPassword }}
      {{- $jupyterToken = .Values.jupyter.token | b64enc }}
    {{- else }}
      {{- $jupyterToken = randAlphaNum 32 | b64enc }}
    {{- end }}
  {{- end }}
  token: {{ $jupyterToken | quote }}