apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter
  labels:
    app: jupyter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter
  strategy: {}
  template:
    metadata:
      labels:
        app: jupyter
    spec:
      containers:
        - env:
            - name: JUPYTER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: dashboard-creds
                  key: dashboard-password

            - name: JUPYTER_PORT
              value: "8888"
            - name: NOTEBOOK_ARGS
              value: "--NotebookApp.base_url=/jupyter/"
          image: {{ .Values.jupyter.image.repository }}:{{ .Values.jupyter.image.tag }}
          imagePullPolicy: {{ .Values.jupyter.image.pullPolicy }}
          name: nemesis-jupyter
          ports:
            - containerPort: 8888
              name: http
          readinessProbe:
            httpGet:
              path: /jupyter/api
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 10
            
      restartPolicy: Always
status: {}
