apiVersion: v1
kind: Secret
metadata:
  name: minio-creds
type: Opaque
data:
  root-user: {{ .Values.minio.rootUser | b64enc | quote }}

  {{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace "minio-creds") | default dict }}
  {{- $existingSecretData := (get $existingSecret "data") | default dict }}
  {{- $minioRootPassword := (get $existingSecretData "root-password") }}
  {{- if not $minioRootPassword }}
    {{- if .Values.minio.rootPassword }}
      {{- $minioRootPassword = .Values.minio.rootPassword | b64enc }}
    {{- else }}
      {{- $minioRootPassword = randAlphaNum 32 | b64enc }}
    {{- end }}
  {{- end }}
  root-password: {{ $minioRootPassword | quote }}