apiVersion: v1
kind: Secret
metadata:
  name: operation-creds
type: Opaque
data:
  basic-auth-user: {{ default "nemesis" .Values.operation.basicAuthUser | b64enc | quote }}

  {{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace "operation-creds") | default dict }}
  {{- $existingSecretData := (get $existingSecret "data") | default dict }}
  {{- $basicAuthPassword := (get $existingSecretData "basic-auth-password") | default (randAlphaNum 24 | b64enc) }}
  basic-auth-password: {{ $basicAuthPassword | quote }}

  slack_web_hook: {{ .Values.operation.slackWebhook | b64enc | quote }}