apiVersion: batch/v1
kind: Job
metadata:
  name: pre-delete-job
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      serviceAccountName: secret-manager
      containers:
      - name: pre-delete
        image: bitnami/kubectl:latest
        command: ["kubectl", "delete", "secret", "basic-auth", "nemesis-ingress-tls", "--ignore-not-found"]
      restartPolicy: Never