{{ if eq .Values.operation.environment "production" }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-data-pv
  labels:
    type: local
    app: rabbitmq
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.rabbitmq.storage }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/rabbitmq/"
{{ end }}