apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-creds
type: Opaque
data:
  {{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace "rabbitmq-creds") | default dict }}
  {{- $existingSecretData := (get $existingSecret "data") | default dict }}

  rabbitmq-admin-user: {{ default "nemesis" .Values.rabbitmq.adminUser | b64enc }}

  {{- $adminPassword := (get $existingSecretData "rabbitmq-admin-password") }}
  {{- if not $adminPassword }}
    {{- if .Values.rabbitmq.adminPassword }}
      {{- $adminPassword = .Values.rabbitmq.adminPassword | b64enc }}
    {{- else }}
      {{- $adminPassword = randAlphaNum 32 | b64enc }}
    {{- end }}
  {{- end }}
  rabbitmq-admin-password: {{ $adminPassword | quote }}

  rabbitmq-connectionuri: {{ .Values.rabbitmq.connectionUri | b64enc }}

  {{- $erlangCookie := (get $existingSecretData "rabbitmq-erlang-cookie") | default (randAlphaNum 24 ) }}
  rabbitmq-erlang-cookie: {{ $erlangCookie | b64enc }}