apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: nemesis
    app.kubernetes.io/component: rabbitmq-server
  name: nemesis-rabbitmq-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: nemesis
    app.kubernetes.io/component: rabbitmq-server
  name: nemesis-rabbitmq-endpoint-reader
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: nemesis
    app.kubernetes.io/component: rabbitmq-server
  name: nemesis-rabbitmq-endpoint-reader
roleRef:
  kind: Role
  name: nemesis-rabbitmq-endpoint-reader
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: nemesis-rabbitmq-sa