apiVersion: v1
kind: Service
metadata:
  labels:
    app: tika
  name: tika
spec:
  type: NodePort
  ports:
    - name: "9998"
      port: 9998
      targetPort: 9998
      nodePort: {{ .Values.tika.nodePort }}
  selector:
    app: tika
status:
  loadBalancer: {}
