apiVersion: v1
kind: Service
metadata:
  name: tensorflow-serving
  labels:
    app: tensorflow-serving
    component: enrichment-pipeline
spec:
  type: NodePort
  ports:
    - name: "8501"
      port: 8501
      targetPort: 8501
      nodePort: 31501
  selector:
    app: tensorflow-serving
status:
  loadBalancer: {}
