apiVersion: v1
kind: Service
metadata:
  name: nlp
  labels:
    app: nlp
    component: enrichment-pipeline
spec:
  type: NodePort
  ports:
    - name: "9803"
      port: 9803
      targetPort: 9803
      nodePort: 31803
    - name: "8000"
      port: 8000
      targetPort: 8000
      nodePort: 31692
  selector:
    app: nlp
status:
  loadBalancer: {}
