apiVersion: v1
kind: ConfigMap
metadata:
  name: tika-config
data:
  tika-config.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <properties>
      <server>
        <params>
          <maxRestarts>10</maxRestarts>
          <maxFiles>10</maxFiles>
          <timeoutThresholdMillis>125000</timeoutThresholdMillis>
        </params>
      </server>
    </properties>